name: diplomska
version: 0.1.0.0
github: "githubuser/diplomska"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/diplomska#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant
  - servant-server
  - wai
  - wai-cors
  - warp
  - text
  - time
  - base-compat-batteries
  - mtl
  - attoparsec
  - bytestring
  - string-conversions
  - lucid
  - http-media
  - directory
  - blaze-markup
  - blaze-html
  - array
  - acid-state
  - safecopy
  - lens
  - vector
  - transformers
  - scientific
  - hashable
  - containers
  - unordered-containers
  - servant-elm
  - elm-bridge
  - http-types

library:
  source-dirs: server/src

executables:
  server:
    main: Main.hs
    source-dirs: server
    ghc-options:
      # - -threaded
      # - -eventlog
      # - -with-rtsopts=-N8
      # - -with-rtsopts=-qg
      # - -with-rtsopts=-I0
      # - -with-rtsopts=-H
      # - -with-rtsopts=-qn1
      # - -with-rtsopts=-l
      - -rtsopts
      - -O2
    dependencies:
      - base
      - diplomska
