name: timeseries-db
version: 0.1.0.0
github: "adrianotm/timeseries-db"
license: BSD3
author: "Adrian Cholak"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/adrianotm/timeseries-db#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - servant
  - servant-server
  - wai
  - wai-cors
  - warp
  - text
  - time
  - bytestring
  - mtl
  - array
  - acid-state
  - safecopy
  - lens
  - vector
  - transformers
  - scientific
  - hashable
  - containers
  - unordered-containers
  - servant-elm
  - elm-bridge
  - http-types
  - deepseq
  - mono-traversable

library:
  source-dirs: server/src

executables:
  server:
    main: Main.hs
    source-dirs: server
    ghc-options:
      - -threaded
      - '"-with-rtsopts=-xn -I0"' #-O
      - -fexcess-precision
      - -funfolding-use-threshold=16
      - -optc-O3
      - -optc-ffast-math
      - -eventlog
      - -Wall
      - -O2
    dependencies:
      - base
      - timeseries-db
